### DISCUSSION TITLE
flexget with rtorrent in docker compose?

### DISCUSSION THREAD

**Discussion by binamov** [jesec/rtorrent#78] [Q&A] [answered]
I've set up flood and rtorrent using docker compose using the `/config/.local/share/rtorrent/rtorrent.sock` socket path, but when I try to do the same with the [flexget rtorrent plugin](https://flexget.com/Plugins/rtorrent) I keep getting 503 errors when flexget tries to interact with rtorrent.

My flexget rtorrent settings say:
```
      uri: /config/.local/share/rtorrent/rtorrent.sock
      path: /config/.local/share/rtorrent/download/
```
I can exec into the flexget container and both paths are reachable.

docker compose looks like this:

```
  rtorrent:
    hostname: rtorrent
    user: 0:0
    image: jesec/rtorrent
    restart: unless-stopped
    ports:
      - "50001:50001"
    environment:
      HOME: /config
    volumes:
      - ./rtorrent:/config
      - rtorrent_session:/home/rtorrent/rtorrent/.session
      - /home/downloads:/home/rtorrent/rtorrent/download

  flexget:
    user: 0:0
    image: flexget/flexget
    restart: unless-stopped
    volumes:
      - ./rtorrent:/config
      - /home/downloads:/home/rtorrent/rtorrent/download
    command:
      - daemon
      - start
      - --autoreload-config


  flood:
    user: 0:0
    image: jesec/flood:latest
    restart: unless-stopped
    command: --allowedpath /home/rtorrent/rtorrent/download --rundir=/config
    volumes: 
      - ./rtorrent:/config
      - /home/downloads:/data
      - /home/downloads:/home/rtorrent/rtorrent/download


```

I get the following stacktrace:

```

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f7669420860>
    └ <Thread(task_queue, started daemon 140146393631544)>
  File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f7669420540>
    └ <Thread(task_queue, started daemon 140146393631544)>
  File "/usr/local/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(task_queue, started daemon 140146393631544)>
    │    │        │    └ ()
    │    │        └ <Thread(task_queue, started daemon 140146393631544)>
    │    └ <bound method TaskQueue.run of <flexget.task_queue.TaskQueue object at 0x7f76607e9690>>
    └ <Thread(task_queue, started daemon 140146393631544)>
  File "/usr/local/lib/python3.11/site-packages/flexget/task_queue.py", line 46, in run
    self.current_task.execute()
    │    │            └ <function Task.execute at 0x7f76652bf4c0>
    │    └ <flexget.task.Task object at 0x7f7660201e50>
    └ <flexget.task_queue.TaskQueue object at 0x7f76607e9690>
  File "/usr/local/lib/python3.11/site-packages/flexget/task.py", line 88, in wrapper
    return func(self, *args, **kw)
           │    │      │       └ {}
           │    │      └ ()
           │    └ <flexget.task.Task object at 0x7f7660201e50>
           └ <function Task.execute at 0x7f76652bf420>
  File "/usr/local/lib/python3.11/site-packages/flexget/task.py", line 717, in execute
    self._execute()
    │    └ <function Task._execute at 0x7f76652bf380>
    └ <flexget.task.Task object at 0x7f7660201e50>
  File "/usr/local/lib/python3.11/site-packages/flexget/task.py", line 686, in _execute
    self.__run_task_phase(phase)
    │                     └ 'output'
    └ <flexget.task.Task object at 0x7f7660201e50>
  File "/usr/local/lib/python3.11/site-packages/flexget/task.py", line 515, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
               │                 │       │      └ (<flexget.task.Task object at 0x7f7660201e50>, {'uri': '/config/.local/share/rtorrent/rtorrent.sock', 'path': '/config/.local...
               │                 │       └ 'output'
               │                 └ <PluginInfo(name=rtorrent)>
               └ <flexget.task.Task object at 0x7f7660201e50>
  File "/usr/local/lib/python3.11/site-packages/flexget/task.py", line 548, in __run_plugin
    result = method(*args, **kwargs)
             │       │       └ {}
             │       └ (<flexget.task.Task object at 0x7f7660201e50>, {'uri': '/config/.local/share/rtorrent/rtorrent.sock', 'path': '/config/.local...
             └ <Event(name=plugin.rtorrent.output,func=on_task_output,priority=135)>
  File "/usr/local/lib/python3.11/site-packages/flexget/event.py", line 21, in __call__
    return self.func(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ (<flexget.task.Task object at 0x7f7660201e50>, {'uri': '/config/.local/share/rtorrent/rtorrent.sock', 'path': '/config/.local...
           │    └ <bound method RTorrentOutputPlugin.on_task_output of <flexget.plugins.clients.rtorrent.RTorrentOutputPlugin object at 0x7f766...
           └ <Event(name=plugin.rtorrent.output,func=on_task_output,priority=135)>
  File "/usr/local/lib/python3.11/site-packages/flexget/plugins/clients/rtorrent.py", line 549, in on_task_output
    self.add_entry(
    │    └ <function RTorrentOutputPlugin.add_entry at 0x7f7662f18360>
    └ <flexget.plugins.clients.rtorrent.RTorrentOutputPlugin object at 0x7f766089ee90>
> File "/usr/local/lib/python3.11/site-packages/flexget/plugins/clients/rtorrent.py", line 743, in add_entry
    resp = client.load(
           │      └ <function RTorrent.load at 0x7f7662ef7880>
           └ <flexget.plugins.clients.rtorrent.RTorrent object at 0x7f765f99a350>
  File "/usr/local/lib/python3.11/site-packages/flexget/plugins/clients/rtorrent.py", line 278, in load
    result = self._server.execute.throw('', 'mkdir', '-p', fields['directory'])
             │    │                                        └ {'directory': '/config/.local/share/rtorrent/download/'}
             │    └ <ServerProxy for 1/RPC2>
             └ <flexget.plugins.clients.rtorrent.RTorrent object at 0x7f765f99a350>
  File "/usr/local/lib/python3.11/xmlrpc/client.py", line 1122, in __call__
    return self.__send(self.__name, args)
           │           │            └ ('', 'mkdir', '-p', '/config/.local/share/rtorrent/download/')
           │           └ <xmlrpc.client._Method object at 0x7f765f966450>
           └ <xmlrpc.client._Method object at 0x7f765f966450>
  File "/usr/local/lib/python3.11/xmlrpc/client.py", line 1464, in __request
    response = self.__transport.request(
               └ <ServerProxy for 1/RPC2>
  File "/usr/local/lib/python3.11/xmlrpc/client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
           │    │              │     │        │             └ False
           │    │              │     │        └ b"<?xml version='1.0'?>\n<methodCall>\n<methodName>execute.throw</methodName>\n<params>\n<param>\n<value><string></string></v...
           │    │              │     └ '/RPC2'
           │    │              └ '1'
           │    └ <function SCGITransport.single_request at 0x7f7662ef7560>
           └ <flexget.plugins.clients.rtorrent.SCGITransport object at 0x7f7660209dd0>
  File "/usr/local/lib/python3.11/site-packages/flexget/plugins/clients/rtorrent.py", line 145, in single_request
    return self.parse_response(response_body)
           │    │              └ <_io.BytesIO object at 0x7f765f742200>
           │    └ <function Transport.parse_response at 0x7f766431b600>
           └ <flexget.plugins.clients.rtorrent.SCGITransport object at 0x7f7660209dd0>
  File "/usr/local/lib/python3.11/xmlrpc/client.py", line 1354, in parse_response
    return u.close()
           │ └ <function Unmarshaller.close at 0x7f7664319620>
           └ <xmlrpc.client.Unmarshaller object at 0x7f765f73e7d0>
  File "/usr/local/lib/python3.11/xmlrpc/client.py", line 668, in close
    raise Fault(**self._stack[0])
          │       │    └ [{'faultCode': -503, 'faultString': 'Bad return code.'}]
          │       └ <xmlrpc.client.Unmarshaller object at 0x7f765f73e7d0>
          └ <class 'xmlrpc.client.Fault'>

```
