### ISSUE TITLE
Docker issue with rtorrent socket on Windows

### ISSUE THREAD

**Issue by beeeeeeep** [jesec/rtorrent#15]
I'm trying to use the rtorrent Docker image on Windows with sockets, using WSL 2 Ubuntu 20.04. I get the following error:

`rtorrent: Error in option file: ~/.rtorrent.rc:143: Could not prepare socket for listening: Not supported`

Here's the relevent bit of my docker-compose.yml:
```
rtorrent:
    image: jesec/rtorrent
    user: ${DOCKER_USER}:${DOCKER_GROUP}
    restart: unless-stopped
    command: -o network.port_range.set=50000-50000,system.daemon.set=true
    environment:
      HOME: /config
    volumes:
      - ./rtorrent_config:/config
      - ${TORRENTS}:/torrents
    network_mode: "service:openvpn"
    depends_on:
      - "openvpn"
```
And line 143 of .rtorrent.rc is

`network.scgi.open_local = /config/.local/share/rtorrent/rtorrent.sock`
