### ISSUE TITLE
docker iamge not running

### ISSUE THREAD

**Issue by SinTan1729** [jesec/rtorrent#56]
I'm trying to run `rtorrent` inside docker with [this image](https://hub.docker.com/r/jesec/rtorrent). But all I get is an error
```
rtorrent: std::bad_alloc
rtorrent: std::bad_alloc
rtorrent: std::bad_alloc
rtorrent: std::bad_alloc
rtorrent: std::bad_alloc
```
This is my `compose.yaml` file:
```
services:
    rtorrent:
        hostname: rtorrent
            image: jesec/rtorrent:0.9.8-r16
            container_name: rtorrent
            user: 1000:1000
            restart: unless-stopped
            command: -o network.port_range.set=6881:6881, system.daemon.set=true
            environment:
                HOME: /config
            volumes:
                - ./dlconfig:/config
                - ./data:/data
            ports:
                - 6881:6881
```
I'm not sure what exactly is going wrong here.
